POST localhost:9999/login

-d username=res-admin
-d password=password

{%
    _G.gas_header("Set-Cookie", "JSESSIONID.-;", context, "JID_R")
%}

POST localhost:9999/login

-d username=user
-d password=password

{%
    _G.gas_header("Set-Cookie", "JSESSIONID.-;", context, "JID_R")
%}

GET localhost:9999/ingredients
Cookie: {{JID_R}}

-u res-admin:password

PUT localhost:9999/ingredients
Cookie: {{JID_R}}
Content-Type: application/json

{
    "id": "SALD",
    "name": "Fresh Salad",
    "type": "VEGGIES"
}
