server:
  port: 9999

logging:
  level:
    org:
      apache:
        logging: DEBUG
      springframework:
        web: DEBUG
        # web:
        #   filter:
        #     CommonsRequestLoggingFilter: DEBUG
    resourceserver: TRACE
    httpclient:
      wire: DEBUG


spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
          audiences: res-admin-client

management:
  endpoints:
    web:
      exposure:
        include: "*"

auth-server:
  client-registrar:
    client-id: r-c-registrar
    secret: secret


