server:
  port: 9999

logging:
  level:
    org:
      springframework:
        web: TRACE
        security: TRACE
    resourceserver: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          auth-server:
            client-id: rs-client
            client-secret: secret
            redirect-uri: http://127.0.0.1:9999/oauth2/authorized/auth-server
            scope: profile
            authorization-grant-type: authorization_code
        provider:
          auth-server:
            issuer-uri: http://localhost:9000

            #      resourceserver:
            #        jwt:
            #          issuer-uri: http://localhost:9000
            #          audiences: res-admin-client

management:
  endpoints:
    web:
      exposure:
        include: "*"

auth-server:
  client-registrar:
    client-id: r-c-registrar
    secret: secret
