GET localhost:9000/.well-known/oauth-authorization-server
GET localhost:9000/.well-known/openid-configuration
#Cookie: {{JID2}}


POST http://localhost:9000/login
Content-Type: application/x-www-form-urlencoded

--data-urlencode username=habuma
--data-urlencode password=password

{%
  _G.gas_header("Set-Cookie", "JSESSIONID=.-;", context, "JID2")
%}

GET http://localhost:9000/oauth2/authorize?response_type=code&client_id=taco-admin-client
Cookie: {{JID2}} 

-G
-d scope=deleteIngredients

{%
  _G.gas_header("Location", "code=.*", context, "CODE")
%}

POST http://localhost:9000/oauth2/authorize
Content-type: application/x-www-form-urlencoded
Cookie: {{JID2}}


--data-urlencode client_id=taco-admin-client
--data-urlencode state=8gkzjGp5bGIurGwjB9c1Lprl45jq2Aq2qnD2dXwfifw=
--data-urlencode scope=deleteIngredients

{%
  _G.gas_header("Location", "code=.*", context, "CODE")
%}

#GET token
POST http://localhost:9000/oauth2/token
Content-type: application/x-www-form-urlencoded

-d grant_type=authorization_code
-d redirect_uri=http://127.0.0.1:9000/login/oauth2/code/taco-admin-client
-u taco-admin-client:secret

{{CODE}}

{%
  _G.gas_json("access_token", context, "TOKEN")
  _G.gas_json("refresh_token", context, "REF_TOKEN")
%}

##refresh
POST http://localhost:9000/oauth2/token
Content-type: application/x-www-form-urlencoded
Cookie: {{JID2}}

-d grant_type=refresh_token
-u taco-admin-client:secret

refresh_token={{REF_TOKEN}}

{%
  _G.gas_json("access_token", context, "TOKEN")
  _G.gas_json("refresh_token", context, "REF_TOKEN")
%}

